services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - NODE_ENV=development
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=admin123
  #     - POSTGRES_DB=sales_db
  #     - POSTGRES_HOST=db
  #     - POSTGRES_PORT=5432
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #     - /app/dist

  db:
    image: postgres:16
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=sales_db
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: